### ISSUE TITLE
这个工具好像只能窃取一次？

### ISSUE THREAD

**Issue by jianxiaohong** [ph4ntonn/Impost3r#3]
我刚才测试了一下，窃取成功了，然后再想着测试一下，就怎么也没回显了。

**Comment by jianxiaohong** [comment]
抱歉大佬，我疏忽了，这个自动清理确实很不错，成功抓取之后就自动清理痕迹了(忘记bashrc这个文件也被清理了)。如果输入的sudo密码不对，则不回当即返回错误的密码。直到输入正确的密码为止，将正确密码和错误密码一起返回。

**Comment by ph4ntonn** [comment]
> 抱歉大佬，我疏忽了，这个自动清理确实很不错，成功抓取之后就自动清理痕迹了(忘记bashrc这个文件也被清理了)。如果输入的sudo密码不对，则不回当即返回错误的密码。直到输入正确的密码为止，将正确密码和错误密码一起返回。

抱歉抱歉，我才看到issue.这个就是窃取一次的，直到成功为止，因为一个用户的sudo密码就只有一个嘛，没必要多次窃取，多次窃取反而会增加暴露的风险.
最后谢谢你的issue～有更多问题欢迎issue或者pr～
