### ISSUE TITLE
师傅您好有以下报错

### ISSUE THREAD

**Issue by 98Kstar** [ph4ntonn/Impost3r#4]
师傅您好，我在一台centos7 的机器上，安装了gcc等依赖工具，在使用ssh_su进行make的时候，出现以下报错，提示文件夹不存在，希望师傅有空帮忙解答
gcc -Werror -Wall -shared -fPIC -Xlinker -x -o impost3r.so main.c ../dns/dns.c ../encode/base32.c
main.c:4:31: fatal error: security/pam_appl.h: No such file or directory
 #include <security/pam_appl.h>

**Comment by ph4ntonn** [comment]
试试这个

sudo yum install gcc pam-devel

**Comment by 98Kstar** [comment]
安装之后还是相同的报错。
gcc -Werror -Wall -shared -fPIC -Xlinker -x -o impost3r.so main.c ../dns/dns.c ../encode/base32.c
main.c:4:31: fatal error: security/pam_appl.h: No such file or directory
 #include <security/pam_appl.h>
怎么感觉是少文件似的。。。

**Comment by 98Kstar** [comment]
可以了谢谢师傅

**Comment by ph4ntonn** [comment]
没事～
