### ISSUE TITLE
Centos7.7 fail

### ISSUE THREAD

**Issue by Udie1wwe** [ph4ntonn/Impost3r#6]
I try it in an Centos 7.7 but when I add the config into the sshd file, the ssh root@192.168.x.x screen "Authentication Fail". I want to know why does it happen? Thanks man

**Comment by ph4ntonn** [comment]
Sorry for responding so late
Centos config is different from Ubuntu which I used as the example in README
So you should check the sshd config file and make sure the logic is right after added Impost3r's config
